####################################################################
iShineId=ricky.rawani@apmosys.com
iShinePassword=Ricky@6501
#iShineId=bhabagrahi.rout@apmosys.com
#iShinePassword=Bhaba@786
reVerify=Y
project=
clientName=
clientLocation=Mahape
teamName=Automation framework Team | Automation framework Team
activity=DB data insertion #Git Project Maintainance #Merging script#R&D #Script Issue Fixing#Script Refactoring #Test Script Execution #Test Script Preparation #Test Script troubleshooting#Test Script Validation
description=




######################FOR Zone#######################################

