jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://192.168.9.16:3306/nonsbi_final_15jan2025
jdbc.username=root
jdbc.password=V2VsY29tZUAyMDIz

########################### SynMonitoring ########################

finalLoopValue=1
makerMobileNo=8847828695
checkerMobileNo=9853311588
businessHourRunStatus=0
businessHourFunctions=LIC_BILLDESK
onMarket=nF
headless=false

otp.makerMobileNo=8591462635
otp.checkerMobileNo=
secondValue=2
##########################  v4 New Key #################
logoutStatus=N
logoutPageName=Logout Page
exitStatus=Y

#Axis_Neo=8591960948
Axis_Neo_Maker=8591109237
otp.jdbc.driver=com.mysql.cj.jdbc.Driver
otp.jdbc.url=jdbc:mysql://192.168.12.74:3306/test?connectTimeout=5000
otp.jdbc.username=admin
otp.jdbc.password=Apmosys@123

future_otp=9167640945
BJAZLI=9029940629
Axis_OTP=99321975713
userMobile=4379612287
#Maker=4379612287



scType=n
runInJenkins = Y
otp.jdbc.driver1=com.mysql.cj.jdbc.Driver
otp.jdbc.url1=jdbc:mysql://192.168.12.74:3306/test?connectTimeout=5000&useSSL=false
otp.jdbc.username1=admin
otp.jdbc.password1=Apmosys@123
#Axis=9321975713
Axis_OTP=8591960927


URL=https://www.smsgateway.center/SMSApi/rest/send?
userId=bibhu
SMSpassword=ApMoSys@0210
senderId=APMSYS
msg=Level test Error on test Page test at test on test for test
mobile=8338065853

popup=y
mailAlert=N
alertmailTo=ankit.jaiswal@apmosys.com
alertmailCC=chandrakant.jadhav@apmosys.com
#mail send properties
host=apmosys.icewarpcloud.in
port=587
mailFrom=alerts@apmosys.com
authId=
password=Deskno@2022
subject= 
message= 
mailTo=ankit.jaiswal@apmosys.com
mailCc=chandrakant.jadhav@apmosys.com
errorMsg=
extraMsg=
monitoringBusinessHour=n

#otp mail for Edelweiss
mailIdOtp=monitoring4apmosys@gmail.com
passOtp=zohf fumw rvty acpz

#Details For Custom Jar
customJarPath=CustomJar/NewCustomJar.jar
customClassName=com.customjar.custommethods.CustomiseFunctions
