####################################################################
runInJenkins=Y
finalLoopValue=1
bankHoliday=n
headless=false

######################FOR DB#######################################
#jdbc.password=T3BlcmF0aW9uQDEyMw==
#jdbc.username=SynMonitoring
#jdbc.driver=com.mysql.cj.jdbc.Driver
#jdbc.url=jdbc:mysql://192.168.1.228:3306/nonsbi_final?connectTimeout=5000

#UAT
jdbc.url=jdbc:mysql://192.168.12.74:3306/nonsbi_final_29Apr?connectTimeout=5000
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.username=apmosys
jdbc.password=QXBtb3N5c0AxMjM=

######################FOR OTP#######################################
otp.jdbc.driver=com.mysql.jdbc.Driver
otp.jdbc.url=jdbc:mysql://114.79.172.202:3306/test?connectTimeout=5000&useSSL=false
otp.jdbc.username=root
otp.jdbc.password=Apmosys@123
#otp.makerMobileNo=8591462635
#otp.makerMobileNo=8828417633
#otp.checkerMobileNo=916764094
Corporate_OTP=8591462618
Authoriser_OTP=9321975713
Maker_OTP=8591462615
sbi_otp=8591462618
SBI=9372669410
Axis_OTP=9076332680
secondValue=5


monitoringBusinessHour=n
monitoringDataSheetPath=
businessHourRunStatus=
businessHourFunctions=
########################## for error alrt ################################
mailAlert=N
alertmailTo=
alertmailCC=

######################FOR MAIL ALERT################################
host=apmosys.icewarpcloud.in
port=587
authId=
mailFrom=alerts1@apmosys.com
password=Deskno@2025
subject= 
message= 
mailTo=sachin.g@apmosys.com
mailCc=anupam.mohanty@apmosys.com,bhabagrahi.rout@apmosys.com
errorMsg=
extraMsg=
####################################################################

#businessHourRunStatus=1
#businessHourFunctions=SbI_Add_Manage_Beneficiary_BusinessHour

onMarket=n
scType=n

URL=https://www.smsgateway.center/SMSApi/rest/send?
userId=bibhu
SMSpassword=ApMoSys@0210
senderId=APMSYS
msg=Level test Error on test Page test at test on test for test
mobile=8338065853

#for monitoring business hour 
monitoringBusinessHour=n
monitoringDataSheetPath=n

#/home/apmosys/bkp/eclipse-workspace/4Oct2022/SBI_NONSBI_HAR/HARFolder/
#HAR PROPERTIES
harPath = /home/apmosys/bkp/eclipse-workspace/4Oct2022/SBI_NONSBI_HAR/HARFolder/
har_generation = Y

